package augustus;

import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;

import augustus.exception.AugustusException;
import augustus.parser.Parser;
import augustus.storage.TaskStorage;
import augustus.task.Deadline;
import augustus.task.Event;
import augustus.task.Task;
import augustus.task.TaskList;
import augustus.task.ToDo;
import augustus.ui.Ui;

/**
 * Represents the main Augustus chatbot application.
 * Coordinates user interaction, task management, parsing, and storage.
 */
public class Augustus {
    private static final String DEFAULT_FILE_PATH = "./src/data/augustus.txt";

    private final TaskStorage storage;
    private TaskList tasks;
    private final Ui ui;

    /**
     * Creates an Augustus chatbot using the default storage file.
     */
    public Augustus() {
        this(DEFAULT_FILE_PATH);
    }

    /**
     * Creates an Augustus chatbot using the specified file for task storage.
     *
     * @param filePath Path of the file used to store tasks.
     */
    public Augustus(String filePath) {
        this.ui = new Ui();
        this.storage = new TaskStorage(filePath);
        try {
            storage.createFile();
            tasks = new TaskList(storage.loadTasks());
        } catch (AugustusException e) {
            ui.showMessage(ui.getErrorMessage(e.getMessage()));
            tasks = new TaskList();
        }
    }

    /**
     * Starts the main command loop and processes user commands until the user exits.
     */
    public void run() {
        ui.showMessage(ui.getIntroMessage());

        while (true) {
            String input = ui.readLine();
            String response = getResponse(input);

            ui.showMessage(response);

            if (Parser.getCommand(input).equals("bye")) {
                break;
            }
        }

        ui.closeScanner();
    }

    /**
     * Processes the user's input and returns Augustus's response.
     *
     * @param input user input to process
     * @return response generated by Augustus
     */
    public String getResponse(String input) {
        try {
            String command = Parser.getCommand(input);

            if (command.equals("list")) {
                return handleList();
            } else if (command.equals("find")) {
                return handleFind(input);
            } else if (command.equals("mark")) {
                return handleMark(input);
            } else if (command.equals("unmark")) {
                return handleUnmark(input);
            } else if (command.equals("todo")) {
                return handleTodo(input);
            } else if (command.equals("deadline")) {
                return handleDeadline(input);
            } else if (command.equals("event")) {
                return handleEvent(input);
            } else if (command.equals("delete")) {
                return handleDelete(input);
            } else if (command.equals("tag")) {
                return handleTag(input);
            } else if (command.equals("bye")) {
                return ui.getExitMessage();
            }

            return ui.getCommandsMessage();

        } catch (AugustusException e) {
            return ui.getErrorMessage(e.getMessage());
        }
    }

    /**
     * Handles the todo command by creating and storing a new todo task.
     *
     * @param input User input containing the todo command.
     * @return Response message after adding the task.
     * @throws AugustusException If the todo description is invalid or
     *                           the task cannot be saved.
     */
    private String handleTodo(String input) throws AugustusException {
        String description = Parser.parseTodo(input);
        Task task = new ToDo(description);

        return addTask(task);
    }

    /**
     * Handles the deadline command by creating and storing a new deadline task.
     *
     * @param input User input containing the deadline command.
     * @return Response message after adding the task.
     * @throws AugustusException If the deadline input or date is invalid,
     *                           or the task cannot be saved.
     */
    private String handleDeadline(String input) throws AugustusException {
        String[] details = Parser.parseDeadline(input);

        String description = details[0];
        String dateString = details[1];

        LocalDate by;
        try {
            by = LocalDate.parse(dateString);
        } catch (DateTimeException e) {
            throw new AugustusException("The date is not in yyyy-MM-dd format");
        }

        Task task = new Deadline(description, by);

        return addTask(task);
    }

    /**
     * Handles the event command by creating and storing a new event task.
     *
     * @param input User input containing the event command.
     * @return Response message after adding the task.
     * @throws AugustusException If the event input is invalid or
     *                           the task cannot be saved.
     */
    private String handleEvent(String input) throws AugustusException {
        String[] details = Parser.parseEvent(input);

        String description = details[0];
        String from = details[1];
        String to = details[2];

        Task task = new Event(description, from, to);

        return addTask(task);
    }

    /**
     * Marks the specified task as done.
     *
     * @param input User input containing the task number.
     * @return Response message after marking the task.
     * @throws AugustusException If the task number is invalid.
     */
    private String handleMark(String input) throws AugustusException {
        Task task = getTask(input);

        task.markDone();
        storage.saveTasks(tasks.getTasks());

        return ui.getMarkTaskMessage(task.toString());
    }

    /**
     * Marks the specified task as not done.
     *
     * @param input User input containing the task number.
     * @return Response message after unmarking the task.
     * @throws AugustusException If the task number is invalid.
     */
    private String handleUnmark(String input) throws AugustusException {
        Task task = getTask(input);

        task.markNotDone();
        storage.saveTasks(tasks.getTasks());

        return ui.getUnmarkTaskMessage(task.toString());
    }

    /**
     * Returns the index of the task specified by the user.
     *
     * @param input User input containing the task number.
     * @return Index of the specified task.
     * @throws AugustusException If the task number is invalid.
     */
    private int getTaskIndex(String input) throws AugustusException {
        int num = Parser.parseTaskNumber(input);

        if (num < 1 || num > tasks.getTaskCount()) {
            throw new AugustusException("Write a valid task number");
        }

        return num - 1;
    }

    /**
     * Returns the task specified by the user.
     *
     * @param input User input containing the task number.
     * @return The specified task.
     * @throws AugustusException If the task number is invalid.
     */
    private Task getTask(String input) throws AugustusException {
        return tasks.get(getTaskIndex(input));
    }

    /**
     * Creates a message containing all tasks in the task list.
     *
     * @return Message containing the numbered task list.
     */
    private String handleList() {
        return formatTasks(
                "Behold the tasks recorded under my rule:\n",
                tasks.getTasks()
        );
    }

    /**
     * Handles the find command by searching for tasks containing a keyword.
     *
     * @param input User input containing the find command and keyword.
     * @return Message containing the matching tasks.
     * @throws AugustusException If no valid search keyword is provided.
     */
    private String handleFind(String input) throws AugustusException {
        String keyword = Parser.parseFind(input);
        ArrayList<Task> matchingTasks = tasks.find(keyword);

        return formatTasks(
                "I have searched my records. These tasks match your request:\n",
                matchingTasks
        );
    }

    /**
     * Handles the delete command by removing a task and saving the updated list.
     *
     * @param input User input containing the task number to delete.
     * @return Response message after deleting the task.
     * @throws AugustusException If the task number is invalid or
     *                           the updated task list cannot be saved.
     */
    private String handleDelete(String input) throws AugustusException {
        int index = getTaskIndex(input);
        int previousCount = tasks.getTaskCount();
        Task removedTask = tasks.delete(index);
        assert tasks.getTaskCount() == previousCount - 1
                : "Task count should decrease";

        storage.saveTasks(tasks.getTasks());

        return ui.getDeleteTaskMessage(removedTask.toString())
                + "\n"
                + ui.getTaskCountMessage(tasks.getTaskCount());
    }

    /**
     * Adds a task, saves the task list, and returns the response message.
     *
     * @param task Task to add.
     * @return Response message after adding the task.
     * @throws AugustusException If the task list cannot be saved.
     */
    private String addTask(Task task) throws AugustusException {
        int previousCount = tasks.getTaskCount();
        tasks.add(task);

        assert tasks.getTaskCount() == previousCount + 1
                : "Task count should increase";
        storage.saveTasks(tasks.getTasks());

        return ui.getAddTaskMessage(task.toString())
                + "\n"
                + ui.getTaskCountMessage(tasks.getTaskCount());
    }

    /**
     * Creates a numbered message for the given tasks.
     *
     * @param header Header of the message.
     * @param tasksToDisplay Tasks to include.
     * @return Formatted task list.
     */
    private String formatTasks(String header, ArrayList<Task> tasksToDisplay) {
        StringBuilder message = new StringBuilder(header);

        for (int i = 0; i < tasksToDisplay.size(); i++) {
            message.append(i + 1)
                    .append(". ")
                    .append(tasksToDisplay.get(i))
                    .append("\n");
        }

        return message.toString();
    }

    /**
     * Assigns a tag to the specified task.
     *
     * @param input User input containing the task number and tag.
     * @return Response message after tagging the task.
     * @throws AugustusException If the task number or tag is invalid.
     */
    private String handleTag(String input) throws AugustusException {
        String tag = Parser.parseTag(input);
        Task task = getTask(input);

        task.setTag(tag);
        storage.saveTasks(tasks.getTasks());

        return "This task shall bear the following mark:\n" + task;
    }

    /**
     * Starts the Augustus chatbot application.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        new Augustus().run();
    }
}

